### ISSUE TITLE
Pick Up 

### ISSUE THREAD

**Issue by LeoNas114** [qbcore-framework/qb-recyclejob#12]
Hello when you try to pick up the package you can pick it up everywhere Is It to me?

**Comment by deandum** [comment]
> Hello when you try to pick up the package you can pick it up everywhere Is It to me?

Can you provide exact reproduction steps and what version of the script are you running on? I tried the latest version and I can't pick up the package unless I am next to the designated spot.

**Comment by CptAllen** [comment]
https://discord.com/channels/831626422232678481/958389600374624326

I am having the same issue, you can check it here

**Comment by tom-osborne** [comment]
A person in the qbcore discord reported this same issue and provided the following console screenshot
https://prnt.sc/w-GJHVjBzSy-

`SCRIPT ERROR: @qb-recyclejob/client/main.lua:371 attempt to index a nil value (upvalue 'pickupZone')`

**Comment by amgmacht** [comment]
I finally have the solution to the problem! Here is the FIX!

**client/mani.lua:371** 

**old :**         `pickupZone:destroy()`

change to 

**new :**          `pickupZonedestroy()`

**Comment by deandum** [comment]
> I finally have the solution to the problem! Here is the FIX!
> 
> **-go to qb-recyclejob/client/mani.lua:371**
> 
> **old :** `pickupZone:destroy()`
> 
> change to
> 
> **new :** `pickupZonedestroy()`
> 
> -then just start the script again and it will work you have to go to the respective palette to pick up a package.

This is not a fix. That is not a defined function. Check the documentation for PZ. 

I will take a look into this today.

**Comment by amgmacht** [comment]
That's true, but I've got it so far that I can't pick up a package from anywhere!  that's the main thing I wanted!  otherwise everything worked for me!

**Comment by deandum** [comment]
https://github.com/qbcore-framework/qb-recyclejob/pull/14
