### ISSUE TITLE
Non stop package bug

### ISSUE THREAD

**Issue by Wollffus** [qbcore-framework/qb-recyclejob#18]
Currently having an issue on a fresh QB install that when i recycle, the very first package has a yellow arrow. but after that i can just spam E at the door and get a package, drop off, get a package, drop off etc etc

**Comment by deandum** [comment]
> Currently having an issue on a fresh QB install that when i recycle, the very first package has a yellow arrow. but after that i can just spam E at the door and get a package, drop off, get a package, drop off etc etc

What version of the script are you using if you look in `fxmanifest.lua`? I was not able to replicate it using v2.1.0.

**Comment by erikmeyer08** [comment]
I had the same issue in 2,0. I upgraded to 2.1 and also using qb-target and the issue went away.
