### ISSUE TITLE
Error parsing script

### ISSUE THREAD

**Issue by L1quidSn4ke** [qbcore-framework/qb-recyclejob#19]
[script:qb-recyclejob] Error parsing script @qb-recyclejob/config.lua in resource qb-recyclejob: @qb-recyclejob/config.lua:13: '}' expected (to close '{' at line 1) near 'PickupActionDuration'

Someone in city is trying to do the job and Im seeing this error in console. They cant explain what they are doing, Ill try it and report back.

**Comment by OMikkel** [comment]
Make sure to end each line with a `,`
