### ISSUE TITLE
[BUG] After disconnection at the recycling center, the exit and various functions of the recycling center are disabled.

### ISSUE THREAD

**Issue by Yumuru** [qbcore-framework/qb-recyclejob#33]
**Describe the bug**
After Disconnect in the recycling center, various functions of the recycling center are disabled.
and cannot go outside.

**Expected behavior**
Maybe if the EnterLocation function in the script is called at login at the recycling center, it will also load at login what is needed at the recycling center.

**Comment by JamieT0001** [comment]
I have replicated and will be posting a PR as soon as I get a good fix.
